# Site settings
title: Blog of Charles Green
email: cg@charlesgreen.org
description: "Business & Growth Hacking"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.charlesgreen.org" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  Author : ['Author', '/author/charles', 'fa-user']
  Contact : ['Contact', '/contact', 'fa-envelope-o']
single_footer: '<p>Blog of Charles Green &copy; 2016 <a href="/">latest posts</a></p>'
footer_links:
    About: ['Author', '/author/charles']

# Build settings
markdown: kramdown
